spring:
  application:
    name: social-service
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true
    username: run.app.pet.project@gmail.com
    password: ssisewukvqkmxugm
server:
  port: ${SERVICE_SERVER_PORT}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false

springdoc:
  packages-to-scan: com.runapp.socialservice